env:
  global:
  - GCP_PROJECT_ID=examinfrastructure-295710
  - tf_version=0.13.5
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: NSrbMjiQMc25RPqEbj4VmGm3A9nAojDqtCr25k7dVuQM2m2zQi1C1wxc6eD9TOwxt049fZWdnpcUL4L8UuFm9ieZrZT3JnfL0Vyd4/VFtBQRcwy912EomAInlzxFTO+ALCP/aGhkqYPEeg8+UEIarXD5F1j7cc4gg+vrl3zXgko1wYxMJwW8KTkwRTKbbTuXwzpm/z/zujFTqLksjCJY8zBD6NFNk1l5mH2COCDetHD/bqA/ezP9YFQ4TSxw+0ADhx5kVzgd7l96un/9HwvYyJl3J9t7eYZzTgt1z+Zt4rNNyQFjaXzgoOXfybS1f19VdTlNIOR+R0DyAAxEFElFjEO7Tk+mPI8wAIK6skElIT80KkDQ60lMolTaZjcDzSMHc5Sx3qOgfqbU3kLmD/nkgngnvC3YtyTG9lIACPgys1kjKfOANVV+iFfyklyXJNakSwFQRRsKr0gGC1/ONMMXPJWxoAedCjbED1ACNXI5qpSUbKYhA9Mz8XZeFgu6I5fhkrIkyBA0eApxz83aARj2t+98FkuNcM/g7u4sArgeHeekcZSq4JRqCDf7CN2l+1wybTtruSMCC9T3YoD9HPdiRfWPi+XBYFP1U9B28w8b6BfWBCeOWMtNZGZs/oFsRYjugrUvkvizbqfYDDND5458c0HgxMVKRp2tssS4WMSVems=
  - secure: V8xHuxkfkh3G/7kZdq+6IjbTVoEfkvlb2/Dvm0gMwxAYmjzxeW52LpE7RTY745qPoPXE16JbfViGsBH1Sfl6Gy9cmmZ7f4ofzeiWArbPXrB7bEw9N0WYu6/AnYYaJ8uSY+/XZSykDt7aQ3zylZXw3UiYHPBPaEk6w/7FmmTj0YcDSH9cV+fOBejMUD+SNarTMZXkcA8kEUT6f1Wdik2l2Z20rr+Dbofe+NXdGKOH7jH0ronevmUyXj7o+BoROVt7nfLb4JIYi9B2J9a/JZea3cR+vq4RV1e1VmVkbQsdEmhhaoEHQD1j5BZM8x7GNJ0Iknsd7kL1mzCe35xhmOb/js4q2JU+0Sub8s3X/4vDj7phL+Pdxg36NSkyYO3ys7KGgYsGHWKhaGd2/neo9Fc3EgWZITHWIv0GHQigIREonffaCu1XF2YLhxRfZxjTDNv11uxAdPaiUir7MBGNUDlI9S+iUiC1BtogJ62eJbSUYguJTtazLHX03T99WlH+Qw8FJ89hI8o6o/VAN6fTqV1YYvVqXpwQ3nYTh3apvp8tOUeng8iM/R9oQfaHgOo8thgQkD08QPiMj5xJpi4i2DSEakYLBa5OnFtm6p/hkbo30Ubqy+JU1cFD2iwINzfQYAfQ07N/jZr3fsO6g+K2GgnvrsSIQDoWymZdf3TTwQl0FI0=
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_3bf60d793673_key -iv $encrypted_3bf60d793673_iv
  -in terraform.json.enc -out terraform.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=terraform.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./terraform.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  export TF_VAR_LOGZ_TOKEN=$LOGZ_TOKEN
  export TF_VAR_LOGZ_URL=$LOGZ_URL
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
