env:
  global:
  - GCP_PROJECT_ID=examinfrastructure-295710
  - tf_version=0.13.5
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: vcaaVByP8lrN/l8eZDnxdaeslhXKS/OujElE73obogpExHdP3XxrUSiePQenH5s4v9h3ZuYiQ8QcWLtuBQLbsJ3KqoE2CIr2o+hHw46MMjb7NlBlV6HXpBnNnfXerQqV2tCzXi5ZqLbA4XXCLqPlhF/DG3LEWbkxlwIh40vMEdX9JIbtoemWvh5nV2kxJVxvlDt38kmYEqE7Vbs+q1qXTowpdo45Hzwbf9MdylnwKmUvJNfO04cxLaW2Yt+4oQ6Pz2OPP5Adhr1tDnjZ8chK6IJ69v3tkt86MLJc/gvMUpyaHALkaXBvnbMhls882/7fRjV1OEW3pZafCMX7hMMEAL32M+asH2yxJAArjrP5JT6T4cqjZVe4IOzGwliAl6/ZmUHXRnkN9Q31S74fCVi5hBcoyRmFDSA6PaCCCiK4lo11OHhHzU9IBPclNNV8H5iom1UPC5bYyLfG5sdXONxpa8TicpJCxWIBcHbhNmvpno0l6KLtNLQWGSjniL7BnrZ/1bSxsq0cCzXXmMydl0UExIQI2hp79TUHqoNcDKkE3rPkACDtAjpGd3edIhJIrCbxUdDwQ3cPt6wH3ThoXTp7+56aeD7/ztnfuxdbCOppegPQ0ArPDSkL3Z+u3M9qo81tl4YMJWo+7jJq4XcAA+MAcxq3ofsqt9rnwkJ7AXpHJUw=
  - secure: iB3kUZ6dKpEXnxfa6uHZt/xK+BGAEieDHGFU7JXyZ/1dLVvkSsiuHjR6+9k0NHzpWoboQwHe23eUXnNrHgKse7vpFRhhQkSVIO78/OotYHflTPF9ROGujwtky41kZ0FL7Enr9pQ8Ca2cKS/bR+oEJNLpZbg2oT9pgEHFXtC6J3fqAk18zJjJmSkZdTzBbBaEBRJEYW3p+7UmKhFdRQyBK88qIyMcVxLXQq7lTehPp+QinfIEdjDQ7q2niTuXoKvngf8uj31A2UkClms9wOL0JEYLP8btLfYHzNk/TkrmgaTiAxEhed2zC4Slrl/k7LuJEKj8tSSFO3YXKubSCagsZqY9wF7U/RZx70voaqRcq1TocifI9qAkn5eCeYJVFQGKCENBKyBdfgYFYdCU3KNFXwlbPXKBNjhGQEd2ALY7I73FMzvw4X854FycRt5clO9S2F4QyA5zKT/KA+iBraNRTMa15SJyjQ7HRXU4KgKoiquo4Rtj0qL/Q0MizLpd6347RBFc2ECzzUACjEU0N79EBXg0hNlhPAueu+bqHffLpb70DXccKpJGwMjjWhijRZ+SKIsiWq998lcm17dsKqmiYjdeWhLXrsR7kaySp2DBTGPUx2EaoTpc6Y6jByUW/P5HA3VDwB+awCKs2xQfdmCkzn0b7llXmvCQakWGvDkPAXY=
  - secure: EAIj5HWnzqwHAPhxV48tA6A4UaCGdsuA4aPPsRES5UEBnl3EIJw1n9r74eQb3VTGlNjxoaWfMDdpWQYWFvg8gjGFJcs0rJn2MTHhlRWVwieFzjUI0rcyTIv/OOO/kwDc2Gd6GeMlx5WCYK+wNRD1RtsWmHzhRMVWFsD/jU+XWxWXVVQFCETSFdjSaO8eR9efYPoP4Ksv0GaSGObFeqigEyegLqWoG6DANQ6/pYcgGikgdVAudiSR7K2MxzMEbKzTmnklZHorVSTrt0f6y72auaIu8wShgoIz+335BxQ4WPCzbknvDmJZw54f1x6X+o5esIpThSd54QxxwFMEoPP6Zkw/1luN821rE+1wWGS2K6Mqy935VU0zPHp2/bpk/BiuUtJgXJDd39EO/dGHDmgmtwOTyD3jb7pxkBaXjfyIyvfp12KqTY74HzpCeJ0e/psrrYuqwYrclrKR2sdsjU/4NfEQ+JGwO6/UBG+ZZwUPICDdNn25A11/I5/kup+RIsuQuz1Hht2gYGGO75PL5F5geyfsfMdlLScLpgVgN7cyMwgFk9a+SS9Qqyb8ekhmRb9W2ca9iA/qI8LKai7fEyYsCakNDkUqYLhSVpWe4/dXp5a+gTe1+7XrCrBz92+jom6iNdoCp61dj0bptWRxX1zw4PELUo9/GB/+N5KNeKsXLuk=
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_3bf60d793673_key -iv $encrypted_3bf60d793673_iv
  -in terraform.json.enc -out terraform.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=terraform.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./terraform.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  export TF_VAR_logz_token=$LOGZ_TOKEN
  export TF_VAR_logz_url=$LOGZ_URL
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
